[tool.poetry]
name = "electroweb"
version = "0.1.0"
description = "Electronics network sales application"
authors = ["You <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
django = "^5.1"
djangorestframework = "^3.15"
python-dotenv = "^1.0"
django-filter = "^24.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
